import { NextApiRequest, NextApiResponse, NextPage } from 'next'
import Head from 'next/head'
import { authOptions } from '@api/auth/[...nextauth]'
import { unstable_getServerSession } from "next-auth/next"
import { signIn, useSession} from 'next-auth/react'




const Home: NextPage = () =>  {
const {data} = useSession()


console.log("esto es la data => ", data)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' background'>
        Hola lucas

        <button onClick={() => {signIn('google')}}>SignIn</button>
      </main>
    </>
  )
}

export default Home

// export async function getServerSideProps({req, res}: {req: NextApiRequest, res: NextApiResponse}) {
//   const session = await unstable_getServerSession(req, res, authOptions)

//   if (!session) {
//     return {
//       redirect: {
//         destination: '/',
//         permanent: false,
//       },
//     }
//   }

//   return {
//     props: {
//       session,
//     },
//   }
// }
