import {Chat} from '@components/chat/chat'
import type { NextPage, NextPageContext } from 'next'
import { Session } from 'next-auth'
import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import { SvgLoading } from '@assets/svg'
import { authUserContext } from '@context/authContext'
import { useContext } from 'react'


const Home: NextPage = () => {
const { user } = useContext(authUserContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-zinc-900 flex flex-col justify-center items-center min-h-screen w-full overscroll-none'>
        {/* Hola lucas
        <br />
        <button
          onClick={() => {
            signIn('google')
          }}
        >
          SignIn
        </button> */}
        <Chat session={user}/>
      </main>
    </>
  )
}

export default Home


