import {Chat} from '@components/chat/chat'
import type { NextPage, NextPageContext } from 'next'
import { Session } from 'next-auth'
import { getSession, useSession } from 'next-auth/react'
import Head from 'next/head'
import { SvgLoading } from '@assets/svg'
interface props {
  data: Session
}

const Home: NextPage<props> = ({ data }) => {
  console.log('ts son la props => ', data)

  const { data: session } = useSession()
  console.log('🚀 ~ file: index.tsx:17 ~ session', session)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-zinc-900 flex flex-col justify-center items-center min-h-screen w-full overscroll-none'>
        {/* Hola lucas
        <br />
        <button
          onClick={() => {
            signIn('google')
          }}
        >
          SignIn
        </button> */}
        <Chat session={data}/>
      </main>
    </>
  )
}

export default Home

export async function getServerSideProps(context: NextPageContext) {
  const data = await getSession(context)

  if (!data) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      },
    }
  }

  return {
    props: {
      data,
    },
  }
}
